[package]
name = "actix-web-middleware-cognito"
description = "Middleware for actix-web that helps you validate Cognito tokens"
version = "0.1.0"
authors = ["Roberto Huertas <roberto.huertas@outlook.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/robertohuertasm/actix-web-middleware-cognito"
readme = "README.md"
keywords = ["middleware", "cognito", "actix-web", "actix"]
categories = ["web-programming", "web-programming::http-server"]

exclude = [".github", ".vscode", "Makefile.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
actix-web-httpauth = "0.4.2"
futures = "0.3.5"
log = "0.4.11"
# jwt validation
jsonwebtokens = "1.0.0-alpha.13"
jsonwebtokens-cognito = "0.1.0-alpha.9"

[dev-dependencies]
env_logger = "0.7.1"
actix-cors = "0.2.0"
actix-rt = "1.1.1"
dotenv = "0.15.0"
