[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy"]

[tasks.clippy-z]
install_crate = "cargo-clippy"
toolchain = "nightly"
command = "cargo"
args = ["clippy", "-Z", "unstable-options"]

[tasks.clippy-pedantic]
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy", "--all", "--", "-D", "clippy::pedantic", "-D", "clippy::nursery", "-D", "warnings"]

[tasks.test-single]
command = "cargo"
args = ["test", "single_thread_test", "--", "--test-threads=1", "--ignored"]

[tasks.test-all]
run_task = [
    { name = ["test", "test-single"], parallel = false },
]

[tasks.all]
dependencies = [
    "format",
    "clippy",
    "test-all"
]
